### ISSUE TITLE
📡 Problem with the Faucet

### ISSUE THREAD

**Issue by DrW3RK** [LibertyDSNP/frequency-testnet-faucet#7]
### Faucet Type

Web

### Problem

TypeError: Failed to fetch

**Comment by p5150j** [comment]
@aramikm @wilwade 
![Screenshot 2023-09-21 at 9 08 39 AM](https://github.com/LibertyDSNP/frequency-testnet-faucet/assets/444888/1f47a890-d74f-4653-be29-98c620609e31)

```
faucet.rococo.frequency.xyz/:1 Access to fetch at 'https://faucet-api-rococo.liberti.social/drip/web' from origin 'https://faucet.rococo.frequency.xyz' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
start.fbf0a0a4.js:1     POST https://faucet-api-rococo.liberti.social/drip/web net::ERR_FAILED 504 (Gateway Time-out)
```

**Comment by p5150j** [comment]
issue resolved!
Thanks, @DrW3RK for the report!!
Just tested and we are good!

![Screenshot 2023-09-21 at 11 55 22 AM](https://github.com/LibertyDSNP/frequency-testnet-faucet/assets/444888/84d4b504-7477-4fe4-a75e-bc03c474a0bf)
